mod nestest;

use std::collections::HashMap;
use lazy_static::lazy_static;

lazy_static! {
    static ref NESTEST_ERRORS: HashMap<u16, &'static str> = {
        let mut m = HashMap::new();

        m.insert(0x0001, "BCS failed to branch");
        m.insert(0x0002, "BCS branched when it shouldn't have");
        m.insert(0x0003, "BCC branched when it shouldn't have");
        m.insert(0x0004, "BCC failed to branch");
        m.insert(0x0005, "BEQ failed to branch");
        m.insert(0x0006, "BEQ branched when it shouldn't have");
        m.insert(0x0007, "BNE failed to branch");
        m.insert(0x0008, "BNE branched when it shouldn't have");
        m.insert(0x0009, "BVS failed to branch");
        m.insert(0x000A, "BVC branched when it shouldn't have");
        m.insert(0x000B, "BVC failed to branch");
        m.insert(0x000C, "BVS branched when it shouldn't have");
        m.insert(0x000D, "BPL failed to branch");
        m.insert(0x000E, "BPL branched when it shouldn't have");
        m.insert(0x000F, "BMI failed to branch");
        m.insert(0x0010, "BMI branched when it shouldn't have");
        m.insert(0x0011, "PHP/flags failure (bits set)");
        m.insert(0x0012, "PHP/flags failure (bits clear)");
        m.insert(0x0013, "PHP/flags failure (misc bit states)");
        m.insert(0x0014, "PLP/flags failure (misc bit states)");
        m.insert(0x0015, "PLP/flags failure (misc bit states)");
        m.insert(0x0016, "PHA/PLA failure (PLA didn't affect Z and N properly)");
        m.insert(0x0017, "PHA/PLA failure (PLA didn't affect Z and N properly)");
        m.insert(0x0018, "ORA # failure");
        m.insert(0x0019, "ORA # failure");
        m.insert(0x001A, "AND # failure");
        m.insert(0x001B, "AND # failure");
        m.insert(0x001C, "EOR # failure");
        m.insert(0x001D, "EOR # failure");
        m.insert(0x001E, "ADC # failure (overflow/carry problems)");
        m.insert(0x001F, "ADC # failure (decimal mode was turned on)");
        m.insert(0x0020, "ADC # failure");
        m.insert(0x0021, "ADC # failure");
        m.insert(0x0022, "ADC # failure");
        m.insert(0x0023, "LDA # failure (didn't set N and Z correctly)");
        m.insert(0x0024, "LDA # failure (didn't set N and Z correctly)");
        m.insert(0x0025, "CMP # failure (messed up flags)");
        m.insert(0x0026, "CMP # failure (messed up flags)");
        m.insert(0x0027, "CMP # failure (messed up flags)");
        m.insert(0x0028, "CMP # failure (messed up flags)");
        m.insert(0x0029, "CMP # failure (messed up flags)");
        m.insert(0x002A, "CMP # failure (messed up flags)");
        m.insert(0x002B, "CPY # failure (messed up flags)");
        m.insert(0x002C, "CPY # failure (messed up flags)");
        m.insert(0x002D, "CPY # failure (messed up flags)");
        m.insert(0x002E, "CPY # failure (messed up flags)");
        m.insert(0x002F, "CPY # failure (messed up flags)");
        m.insert(0x0030, "CPY # failure (messed up flags)");
        m.insert(0x0031, "CPY # failure (messed up flags)");
        m.insert(0x0032, "CPX # failure (messed up flags)");
        m.insert(0x0033, "CPX # failure (messed up flags)");
        m.insert(0x0034, "CPX # failure (messed up flags)");
        m.insert(0x0035, "CPX # failure (messed up flags)");
        m.insert(0x0036, "CPX # failure (messed up flags)");
        m.insert(0x0037, "CPX # failure (messed up flags)");
        m.insert(0x0038, "CPX # failure (messed up flags)");
        m.insert(0x0039, "LDX # failure (didn't set N and Z correctly)");
        m.insert(0x003A, "LDX # failure (didn't set N and Z correctly)");
        m.insert(0x003B, "LDY # failure (didn't set N and Z correctly)");
        m.insert(0x003C, "LDY # failure (didn't set N and Z correctly)");
        m.insert(0x003D, "compare(s) stored the result in a register (whoops!)");
        m.insert(0x0071, "SBC # failure");
        m.insert(0x0072, "SBC # failure");
        m.insert(0x0073, "SBC # failure");
        m.insert(0x0074, "SBC # failure");
        m.insert(0x0075, "SBC # failure");
        m.insert(0x003E, "INX/DEX/INY/DEY did something bad");
        m.insert(0x003F, "INY/DEY messed up overflow or carry");
        m.insert(0x0040, "INX/DEX messed up overflow or carry");
        m.insert(0x0041, "TAY did something bad (changed wrong regs, messed up flags)");
        m.insert(0x0042, "TAX did something bad (changed wrong regs, messed up flags)");
        m.insert(0x0043, "TYA did something bad (changed wrong regs, messed up flags)");
        m.insert(0x0044, "TXA did something bad (changed wrong regs, messed up flags)");
        m.insert(0x0045, "TXS didn't set flags right, or TSX touched flags and it shouldn't have");
        m.insert(0x0046, "wrong data popped, or data not in right location on stack");
        m.insert(0x0047, "JSR didn't work as expected");
        m.insert(0x0048, "RTS/JSR shouldn't have affected flags");
        m.insert(0x0049, "RTI/RTS didn't work right when return addys/data were manually pushed");
        m.insert(0x004A, "LSR A  failed");
        m.insert(0x004B, "ASL A  failed");
        m.insert(0x004C, "ROR A  failed");
        m.insert(0x004D, "ROL A  failed");
        m.insert(0x0058, "LDA didn't load the data it expected to load");
        m.insert(0x0059, "STA didn't store the data where it was supposed to");
        m.insert(0x005A, "ORA failure");
        m.insert(0x005B, "ORA failure");
        m.insert(0x005C, "AND failure");
        m.insert(0x005D, "AND failure");
        m.insert(0x005E, "EOR failure");
        m.insert(0x005F, "EOR failure");
        m.insert(0x0060, "ADC failure");
        m.insert(0x0061, "ADC failure");
        m.insert(0x0062, "ADC failure");
        m.insert(0x0063, "ADC failure");
        m.insert(0x0064, "ADC failure");
        m.insert(0x0065, "CMP failure");
        m.insert(0x0066, "CMP failure");
        m.insert(0x0067, "CMP failure");
        m.insert(0x0068, "CMP failure");
        m.insert(0x0069, "CMP failure");
        m.insert(0x006A, "CMP failure");
        m.insert(0x006B, "CMP failure");
        m.insert(0x006C, "SBC failure");
        m.insert(0x006D, "SBC failure");
        m.insert(0x006E, "SBC failure");
        m.insert(0x006F, "SBC failure");
        m.insert(0x0070, "SBC failure");
        m.insert(0x0076, "LDA didn't set the flags properly");
        m.insert(0x0077, "STA affected flags it shouldn't");
        m.insert(0x0078, "LDY didn't set the flags properly");
        m.insert(0x0079, "STY affected flags it shouldn't");
        m.insert(0x007A, "LDX didn't set the flags properly");
        m.insert(0x007B, "STX affected flags it shouldn't");
        m.insert(0x007C, "BIT failure");
        m.insert(0x007D, "BIT failure");
        m.insert(0x007E, "ORA failure");
        m.insert(0x007F, "ORA failure");
        m.insert(0x0080, "AND failure");
        m.insert(0x0081, "AND failure");
        m.insert(0x0082, "EOR failure");
        m.insert(0x0083, "EOR failure");
        m.insert(0x0084, "ADC failure");
        m.insert(0x0085, "ADC failure");
        m.insert(0x0086, "ADC failure");
        m.insert(0x0087, "ADC failure");
        m.insert(0x0088, "ADC failure");
        m.insert(0x0089, "CMP failure");
        m.insert(0x008A, "CMP failure");
        m.insert(0x008B, "CMP failure");
        m.insert(0x008C, "CMP failure");
        m.insert(0x008D, "CMP failure");
        m.insert(0x008E, "CMP failure");
        m.insert(0x008F, "CMP failure");
        m.insert(0x0090, "SBC failure");
        m.insert(0x0091, "SBC failure");
        m.insert(0x0092, "SBC failure");
        m.insert(0x0093, "SBC failure");
        m.insert(0x0094, "SBC failure");
        m.insert(0x0095, "CPX failure");
        m.insert(0x0096, "CPX failure");
        m.insert(0x0097, "CPX failure");
        m.insert(0x0098, "CPX failure");
        m.insert(0x0099, "CPX failure");
        m.insert(0x009A, "CPX failure");
        m.insert(0x009B, "CPX failure");
        m.insert(0x009C, "CPY failure");
        m.insert(0x009D, "CPY failure");
        m.insert(0x009E, "CPY failure");
        m.insert(0x009F, "CPY failure");
        m.insert(0x00A0, "CPY failure");
        m.insert(0x00A1, "CPY failure");
        m.insert(0x00A2, "CPY failure");
        m.insert(0x00A3, "LSR failure");
        m.insert(0x00A4, "LSR failure");
        m.insert(0x00A5, "ASL failure");
        m.insert(0x00A6, "ASL failure");
        m.insert(0x00A7, "ROL failure");
        m.insert(0x00A8, "ROL failure");
        m.insert(0x00A9, "ROR failure");
        m.insert(0x00AA, "ROR failure");
        m.insert(0x00AB, "INC failure");
        m.insert(0x00AC, "INC failure");
        m.insert(0x00AD, "DEC failure");
        m.insert(0x00AE, "DEC failure");
        m.insert(0x00AF, "DEC failure");
        m.insert(0x00B0, "LDA didn't set the flags properly");
        m.insert(0x00B1, "STA affected flags it shouldn't");
        m.insert(0x00B2, "LDY didn't set the flags properly");
        m.insert(0x00B3, "STY affected flags it shouldn't");
        m.insert(0x00B4, "LDX didn't set the flags properly");
        m.insert(0x00B5, "STX affected flags it shouldn't");
        m.insert(0x00B6, "BIT failure");
        m.insert(0x00B7, "BIT failure");
        m.insert(0x00B8, "ORA failure");
        m.insert(0x00B9, "ORA failure");
        m.insert(0x00BA, "AND failure");
        m.insert(0x00BB, "AND failure");
        m.insert(0x00BC, "EOR failure");
        m.insert(0x00BD, "EOR failure");
        m.insert(0x00BE, "ADC failure");
        m.insert(0x00BF, "ADC failure");
        m.insert(0x00C0, "ADC failure");
        m.insert(0x00C1, "ADC failure");
        m.insert(0x00C2, "ADC failure");
        m.insert(0x00C3, "CMP failure");
        m.insert(0x00C4, "CMP failure");
        m.insert(0x00C5, "CMP failure");
        m.insert(0x00C6, "CMP failure");
        m.insert(0x00C7, "CMP failure");
        m.insert(0x00C8, "CMP failure");
        m.insert(0x00C9, "CMP failure");
        m.insert(0x00CA, "SBC failure");
        m.insert(0x00CB, "SBC failure");
        m.insert(0x00CC, "SBC failure");
        m.insert(0x00CD, "SBC failure");
        m.insert(0x00CE, "SBC failure");
        m.insert(0x00CF, "CPX failure");
        m.insert(0x00D0, "CPX failure");
        m.insert(0x00D1, "CPX failure");
        m.insert(0x00D2, "CPX failure");
        m.insert(0x00D3, "CPX failure");
        m.insert(0x00D4, "CPX failure");
        m.insert(0x00D5, "CPX failure");
        m.insert(0x00D6, "CPY failure");
        m.insert(0x00D7, "CPY failure");
        m.insert(0x00D8, "CPY failure");
        m.insert(0x00D9, "CPY failure");
        m.insert(0x00DA, "CPY failure");
        m.insert(0x00DB, "CPY failure");
        m.insert(0x00DC, "CPY failure");
        m.insert(0x00DD, "LSR failure");
        m.insert(0x00DE, "LSR failure");
        m.insert(0x00DF, "ASL failure");
        m.insert(0x00E0, "ASL failure");
        m.insert(0x00E1, "ROR failure");
        m.insert(0x00E2, "ROR failure");
        m.insert(0x00E3, "ROL failure");
        m.insert(0x00E4, "ROL failure");
        m.insert(0x00E5, "INC failure");
        m.insert(0x00E6, "INC failure");
        m.insert(0x00E7, "DEC failure");
        m.insert(0x00E8, "DEC failure");
        m.insert(0x00E9, "DEC failure");
        m.insert(0x00EA, "LDA didn't load what it was supposed to");
        m.insert(0x00EB, "read location should've wrapped around ffffh to 0000h");
        m.insert(0x00EC, "should've wrapped zeropage address");
        m.insert(0x00ED, "ORA failure");
        m.insert(0x00EE, "ORA failure");
        m.insert(0x00EF, "AND failure");
        m.insert(0x00F0, "AND failure");
        m.insert(0x00F1, "EOR failure");
        m.insert(0x00F2, "EOR failure");
        m.insert(0x00F3, "ADC failure");
        m.insert(0x00F4, "ADC failure");
        m.insert(0x00F5, "ADC failure");
        m.insert(0x00F6, "ADC failure");
        m.insert(0x00F7, "ADC failure");
        m.insert(0x00F8, "CMP failure");
        m.insert(0x00F9, "CMP failure");
        m.insert(0x00FA, "CMP failure");
        m.insert(0x00FB, "CMP failure");
        m.insert(0x00FC, "CMP failure");
        m.insert(0x00FD, "CMP failure");
        m.insert(0x00FE, "CMP failure");
        m.insert(0x0000, "no error, all tests pass");
        m.insert(0x0100, "SBC failure");
        m.insert(0x0200, "SBC failure");
        m.insert(0x0300, "SBC failure");
        m.insert(0x0400, "SBC failure");
        m.insert(0x0500, "SBC failure");
        m.insert(0x0600, "STA failure");
        m.insert(0x0700, "JMP () data reading didn't wrap properly (this fails on a 65C02)");
        m.insert(0x0800, "LDY,X failure");
        m.insert(0x0900, "LDY,X failure");
        m.insert(0x0A00, "STY,X failure");
        m.insert(0x0B00, "ORA failure");
        m.insert(0x0C00, "ORA failure");
        m.insert(0x0D00, "AND failure");
        m.insert(0x0E00, "AND failure");
        m.insert(0x0F00, "EOR failure");
        m.insert(0x1000, "EOR failure");
        m.insert(0x1100, "ADC failure");
        m.insert(0x1200, "ADC failure");
        m.insert(0x1300, "ADC failure");
        m.insert(0x1400, "ADC failure");
        m.insert(0x1500, "ADC failure");
        m.insert(0x1600, "CMP failure");
        m.insert(0x1700, "CMP failure");
        m.insert(0x1800, "CMP failure");
        m.insert(0x1900, "CMP failure");
        m.insert(0x1A00, "CMP failure");
        m.insert(0x1B00, "CMP failure");
        m.insert(0x1C00, "CMP failure");
        m.insert(0x1D00, "SBC failure");
        m.insert(0x1E00, "SBC failure");
        m.insert(0x1F00, "SBC failure");
        m.insert(0x2000, "SBC failure");
        m.insert(0x2100, "SBC failure");
        m.insert(0x2200, "LDA failure");
        m.insert(0x2300, "LDA failure");
        m.insert(0x2400, "STA failure");
        m.insert(0x2500, "LSR failure");
        m.insert(0x2600, "LSR failure");
        m.insert(0x2700, "ASL failure");
        m.insert(0x2800, "ASL failure");
        m.insert(0x2900, "ROR failure");
        m.insert(0x2A00, "ROR failure");
        m.insert(0x2B00, "ROL failure");
        m.insert(0x2C00, "ROL failure");
        m.insert(0x2D00, "INC failure");
        m.insert(0x2E00, "INC failure");
        m.insert(0x2F00, "DEC failure");
        m.insert(0x3000, "DEC failure");
        m.insert(0x3100, "DEC failure");
        m.insert(0x3200, "LDX,Y failure");
        m.insert(0x3300, "LDX,Y failure");
        m.insert(0x3400, "STX,Y failure");
        m.insert(0x3500, "STX,Y failure");
        m.insert(0x3600, "LDA failure");
        m.insert(0x3700, "LDA failure to wrap properly from ffffh to 0000h");
        m.insert(0x3800, "LDA failure, page cross");
        m.insert(0x3900, "ORA failure");
        m.insert(0x3A00, "ORA failure");
        m.insert(0x3B00, "AND failure");
        m.insert(0x3C00, "AND failure");
        m.insert(0x3D00, "EOR failure");
        m.insert(0x3E00, "EOR failure");
        m.insert(0x3F00, "ADC failure");
        m.insert(0x4000, "ADC failure");
        m.insert(0x4100, "ADC failure");
        m.insert(0x4200, "ADC failure");
        m.insert(0x4300, "ADC failure");
        m.insert(0x4400, "CMP failure");
        m.insert(0x4500, "CMP failure");
        m.insert(0x4600, "CMP failure");
        m.insert(0x4700, "CMP failure");
        m.insert(0x4800, "CMP failure");
        m.insert(0x4900, "CMP failure");
        m.insert(0x4A00, "CMP failure");
        m.insert(0x4B00, "SBC failure");
        m.insert(0x4C00, "SBC failure");
        m.insert(0x4D00, "SBC failure");
        m.insert(0x4E00, "SBC failure");
        m.insert(0x4F00, "SBC failure");
        m.insert(0x5000, "STA failure");
        m.insert(0x5100, "LDY,X failure");
        m.insert(0x5200, "LDY,X failure (didn't page cross)");
        m.insert(0x5300, "ORA failure");
        m.insert(0x5400, "ORA failure");
        m.insert(0x5500, "AND failure");
        m.insert(0x5600, "AND failure");
        m.insert(0x5700, "EOR failure");
        m.insert(0x5800, "EOR failure");
        m.insert(0x5900, "ADC failure");
        m.insert(0x5A00, "ADC failure");
        m.insert(0x5B00, "ADC failure");
        m.insert(0x5C00, "ADC failure");
        m.insert(0x5D00, "ADC failure");
        m.insert(0x5E00, "CMP failure");
        m.insert(0x5F00, "CMP failure");
        m.insert(0x6000, "CMP failure");
        m.insert(0x6100, "CMP failure");
        m.insert(0x6200, "CMP failure");
        m.insert(0x6300, "CMP failure");
        m.insert(0x6400, "CMP failure");
        m.insert(0x6500, "SBC failure");
        m.insert(0x6600, "SBC failure");
        m.insert(0x6700, "SBC failure");
        m.insert(0x6800, "SBC failure");
        m.insert(0x6900, "SBC failure");
        m.insert(0x6A00, "LDA failure");
        m.insert(0x6B00, "LDA failure (didn't page cross)");
        m.insert(0x6C00, "STA failure");
        m.insert(0x6D00, "LSR failure");
        m.insert(0x6E00, "LSR failure");
        m.insert(0x6F00, "ASL failure");
        m.insert(0x7000, "ASL failure");
        m.insert(0x7100, "ROR failure");
        m.insert(0x7200, "ROR failure");
        m.insert(0x7300, "ROL failure");
        m.insert(0x7400, "ROL failure");
        m.insert(0x7500, "INC failure");
        m.insert(0x7600, "INC failure");
        m.insert(0x7700, "DEC failure");
        m.insert(0x7800, "DEC failure");
        m.insert(0x7900, "DEC failure");
        m.insert(0x7A00, "LDX,Y failure");
        m.insert(0x7B00, "LDX,Y failure");
        m.insert(0x004E, "absolute,X NOPs less than 3 bytes long");
        m.insert(0x004F, "implied NOPs affects regs/flags");
        m.insert(0x0050, "ZP,X NOPs less than 2 bytes long");
        m.insert(0x0051, "absolute NOP less than 3 bytes long");
        m.insert(0x0052, "ZP NOPs less than 2 bytes long");
        m.insert(0x0053, "absolute,X NOPs less than 3 bytes long");
        m.insert(0x0054, "implied NOPs affects regs/flags");
        m.insert(0x0055, "ZP,X NOPs less than 2 bytes long");
        m.insert(0x0056, "absolute NOP less than 3 bytes long");
        m.insert(0x0057, "ZP NOPs less than 2 bytes long");
        m.insert(0x7C00, "LAX (indr,x) failure");
        m.insert(0x7D00, "LAX (indr,x) failure");
        m.insert(0x7E00, "LAX zeropage failure");
        m.insert(0x7F00, "LAX zeropage failure");
        m.insert(0x8000, "LAX absolute failure");
        m.insert(0x8100, "LAX absolute failure");
        m.insert(0x8200, "LAX (indr),y failure");
        m.insert(0x8300, "LAX (indr),y failure");
        m.insert(0x8400, "LAX zp,y failure");
        m.insert(0x8500, "LAX zp,y failure");
        m.insert(0x8600, "LAX abs,y failure");
        m.insert(0x8700, "LAX abs,y failure");
        m.insert(0x8800, "SAX (indr,x) failure");
        m.insert(0x8900, "SAX (indr,x) failure");
        m.insert(0x8A00, "SAX zeropage failure");
        m.insert(0x8B00, "SAX zeropage failure");
        m.insert(0x8C00, "SAX absolute failure");
        m.insert(0x8D00, "SAX absolute failure");
        m.insert(0x8E00, "SAX zp,y failure");
        m.insert(0x8F00, "SAX zp,y failure");
        m.insert(0x9000, "SBC failure");
        m.insert(0x9100, "SBC failure");
        m.insert(0x9200, "SBC failure");
        m.insert(0x9300, "SBC failure");
        m.insert(0x9400, "SBC failure");
        m.insert(0x9500, "DCP (indr,x) failure");
        m.insert(0x9600, "DCP (indr,x) failure");
        m.insert(0x9700, "DCP (indr,x) failure");
        m.insert(0x9800, "DCP zeropage failure");
        m.insert(0x9900, "DCP zeropage failure");
        m.insert(0x9A00, "DCP zeropage failure");
        m.insert(0x9B00, "DCP absolute failure");
        m.insert(0x9C00, "DCP absolute failure");
        m.insert(0x9D00, "DCP absolute failure");
        m.insert(0x9E00, "DCP (indr),y failure");
        m.insert(0x9F00, "DCP (indr),y failure");
        m.insert(0xA000, "DCP (indr),y failure");
        m.insert(0xA100, "DCP zp,x failure");
        m.insert(0xA200, "DCP zp,x failure");
        m.insert(0xA300, "DCP zp,x failure");
        m.insert(0xA400, "DCP abs,y failure");
        m.insert(0xA500, "DCP abs,y failure");
        m.insert(0xA600, "DCP abs,y failure");
        m.insert(0xA700, "DCP abs,x failure");
        m.insert(0xA800, "DCP abs,x failure");
        m.insert(0xA900, "DCP abs,x failure");
        m.insert(0xAA00, "DCP (indr,x) failure");
        m.insert(0xAB00, "DCP (indr,x) failure");
        m.insert(0xAC00, "DCP (indr,x) failure");
        m.insert(0xAD00, "DCP zeropage failure");
        m.insert(0xAE00, "DCP zeropage failure");
        m.insert(0xAF00, "DCP zeropage failure");
        m.insert(0xB000, "DCP absolute failure");
        m.insert(0xB100, "DCP absolute failure");
        m.insert(0xB200, "DCP absolute failure");
        m.insert(0xB300, "DCP (indr),y failure");
        m.insert(0xB400, "DCP (indr),y failure");
        m.insert(0xB500, "DCP (indr),y failure");
        m.insert(0xB600, "DCP zp,x failure");
        m.insert(0xB700, "DCP zp,x failure");
        m.insert(0xB800, "DCP zp,x failure");
        m.insert(0xB900, "DCP abs,y failure");
        m.insert(0xBA00, "DCP abs,y failure");
        m.insert(0xBB00, "DCP abs,y failure");
        m.insert(0xBC00, "DCP abs,x failure");
        m.insert(0xBD00, "DCP abs,x failure");
        m.insert(0xBE00, "DCP abs,x failure");
        m.insert(0xBF00, "SLO (indr,x) failure");
        m.insert(0xC000, "SLO (indr,x) failure");
        m.insert(0xC100, "SLO (indr,x) failure");
        m.insert(0xC200, "SLO zeropage failure");
        m.insert(0xC300, "SLO zeropage failure");
        m.insert(0xC400, "SLO zeropage failure");
        m.insert(0xC500, "SLO absolute failure");
        m.insert(0xC600, "SLO absolute failure");
        m.insert(0xC700, "SLO absolute failure");
        m.insert(0xC800, "SLO (indr),y failure");
        m.insert(0xC900, "SLO (indr),y failure");
        m.insert(0xCA00, "SLO (indr),y failure");
        m.insert(0xCB00, "SLO zp,x failure");
        m.insert(0xCC00, "SLO zp,x failure");
        m.insert(0xCD00, "SLO zp,x failure");
        m.insert(0xCE00, "SLO abs,y failure");
        m.insert(0xCF00, "SLO abs,y failure");
        m.insert(0xD000, "SLO abs,y failure");
        m.insert(0xD100, "SLO abs,x failure");
        m.insert(0xD200, "SLO abs,x failure");
        m.insert(0xD300, "SLO abs,x failure");
        m.insert(0xD400, "RLA (indr,x) failure");
        m.insert(0xD500, "RLA (indr,x) failure");
        m.insert(0xD600, "RLA (indr,x) failure");
        m.insert(0xD700, "RLA zeropage failure");
        m.insert(0xD800, "RLA zeropage failure");
        m.insert(0xD900, "RLA zeropage failure");
        m.insert(0xDA00, "RLA absolute failure");
        m.insert(0xDB00, "RLA absolute failure");
        m.insert(0xDC00, "RLA absolute failure");
        m.insert(0xDD00, "RLA (indr),y failure");
        m.insert(0xDE00, "RLA (indr),y failure");
        m.insert(0xDF00, "RLA (indr),y failure");
        m.insert(0xE000, "RLA zp,x failure");
        m.insert(0xE100, "RLA zp,x failure");
        m.insert(0xE200, "RLA zp,x failure");
        m.insert(0xE300, "RLA abs,y failure");
        m.insert(0xE400, "RLA abs,y failure");
        m.insert(0xE500, "RLA abs,y failure");
        m.insert(0xE600, "RLA abs,x failure");
        m.insert(0xE700, "RLA abs,x failure");
        m.insert(0xE800, "RLA abs,x failure");
        m.insert(0xE800, "SRE (indr,x) failure");
        m.insert(0xEA00, "SRE (indr,x) failure");
        m.insert(0xEB00, "SRE (indr,x) failure");
        m.insert(0xEC00, "SRE zeropage failure");
        m.insert(0xED00, "SRE zeropage failure");
        m.insert(0xEE00, "SRE zeropage failure");
        m.insert(0xEF00, "SRE absolute failure");
        m.insert(0xF000, "SRE absolute failure");
        m.insert(0xF100, "SRE absolute failure");
        m.insert(0xF200, "SRE (indr),y failure");
        m.insert(0xF300, "SRE (indr),y failure");
        m.insert(0xF400, "SRE (indr),y failure");
        m.insert(0xF500, "SRE zp,x failure");
        m.insert(0xF600, "SRE zp,x failure");
        m.insert(0xF700, "SRE zp,x failure");
        m.insert(0xF800, "SRE abs,y failure");
        m.insert(0xF900, "SRE abs,y failure");
        m.insert(0xFA00, "SRE abs,y failure");
        m.insert(0xFB00, "SRE abs,x failure");
        m.insert(0xFC00, "SRE abs,x failure");
        m.insert(0xFD00, "SRE abs,x failure");
        m.insert(0x0100, "RRA (indr,x) failure");
        m.insert(0x0200, "RRA (indr,x) failure");
        m.insert(0x0300, "RRA (indr,x) failure");
        m.insert(0x0400, "RRA zeropage failure");
        m.insert(0x0500, "RRA zeropage failure");
        m.insert(0x0600, "RRA zeropage failure");
        m.insert(0x0700, "RRA absolute failure");
        m.insert(0x0800, "RRA absolute failure");
        m.insert(0x0900, "RRA absolute failure");
        m.insert(0x0A00, "RRA (indr),y failure");
        m.insert(0x0B00, "RRA (indr),y failure");
        m.insert(0x0C00, "RRA (indr),y failure");
        m.insert(0x0D00, "RRA zp,x failure");
        m.insert(0x0E00, "RRA zp,x failure");
        m.insert(0x0F00, "RRA zp,x failure");
        m.insert(0x1000, "RRA abs,y failure");
        m.insert(0x1100, "RRA abs,y failure");
        m.insert(0x1200, "RRA abs,y failure");
        m.insert(0x1300, "RRA abs,x failure");
        m.insert(0x1400, "RRA abs,x failure");
        m.insert(0x1500, "RRA abs,x failure");

        m
    };
}